#!/usr/bin/env sh

# load profile
# (Look like a bug in OpenBSD does not respect loginShell via xenodm)
. "${HOME}/.profile"

# load Xresources file
xrdb -merge "${HOME}/.Xresources"

# Return to safe value
xbacklight -set 100%
xsetroot -cursor_name left_ptr

# Thinkpad
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1 
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2 
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5 

# Background
hsetroot -tile "${HOME}/.wallpaper.png"
exec dbus-run-session cwm
