#!/usr/bin/env sh

# Return to safe value
xbacklight -set 50%
xsetroot -cursor_name left_ptr

# Reset MPC/MPD
mpc load radioparadise
mpc play
mpc pause

# Background
hsetroot -tile ${HOME}/.wallpaper.jpeg
exec cwm
