#!/usr/bin/env sh

source "${HOME}/.profile"

# load Xresources file
xrdb -merge "${HOME}/.Xresources"

# Return to safe value
# xbacklight -set 75%
wsconsctl display.brightness=75%
xsetroot -cursor_name left_ptr

# Thinkpad
if command -v sysctl
then 
    if [[ $(sysctl hw.version | sed -rn 's/^hw.version=(.*)/\1/p') == 'ThinkPad X200s' ]]
    then
        xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1 
        xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2 
        xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5 
    fi
fi

# Background
hsetroot -tile "${HOME}/.wallpaper.png"
dbus-launch cwm

# TODO
# wsconsctl display.brightness=100%
# wsconsctl keyboard.backlight=0%
