#! /bin/sh

background="#d8dee9"
foreground_alt="#4c566a"
primary="#ebcb8b"
secondary="#bf616a"

# bspc monitor DP-4 -d ' ' ' ' ' ' ' ' ' '
# bspc monitor HDMI-0 -d ' ' ' ' ' ' ' ' ' '

bspc config border_width         2
bspc config window_gap           2
bspc config split_ratio          0.58

bspc config focused_border_color "$primary" 
bspc config normal_border_color "$background"
bspc config active_border_color "$foreground_alt"
bspc config presel_feedback_color "$secondary"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false

# bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -r *:*

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a Lxappearance state=floating
bspc rule -a alacritty-floating state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
