#!/usr/bin/env sh

# BSPWM
sxhkd &
xsetroot -cursor_name left_ptr

# Return to safe value
xbacklight -set 50%
amixer -c 1 -q set 'Master' 25%

# Add xrandr logic
xrandr --output DP-4 --left-of HDMI-0

# Add xprop mouse logic
# xinput --list --id-only "$(xinput --list --name-only | grep Corsair)"
# xinput --set-prop 15 309 -0.8

# Background
hsetroot -tile ${HOME}/.wallpaper.jpeg

# Candy
picom --backend glx --vsync --use-ewmh-active-win --dbus -cf &

# FIXME: Rework polybar (Merge and simplify)
~/.config/polybar/material/launch.sh &

if [ -f ~/.bspwm ];
then
  exec dbus-run-session bspwm -c ~/.config/bspwm/bspwmrc
else
  exec dbus-run-session dwm
fi
